// components/ui/EmptyState.tsx
import React from 'react'
import { useRouter } from 'next/router'

interface EmptyStateProps {
  icon?: string
  title?: string
  description?: string
  actionText?: string
  onClear?: () => void
}

const EmptyState: React.FC<EmptyStateProps> = ({
  icon = '🔍',
  title,
  description,
  actionText,
  onClear
}) => {
  const { locale } = useRouter()
  
  const t = {
    title: locale === 'en' ? 'No results found' : '找不到相關結果',
    desc: locale === 'en' 
      ? 'Please try using different keywords or check your spelling.' 
      : '請嘗試使用不同的關鍵字，或者檢查拼字是否正確。'
  }

  return (
    <div className="text-center py-20 px-6 bg-gray-50 dark:bg-zinc-900 rounded-[24px] border border-dashed border-gray-200 dark:border-zinc-800 mt-10">
      <div className="text-5xl mb-5">{icon}</div>
      <h3 className="text-2xl font-bold mb-3">{title || t.title}</h3>
      <p className="text-gray-500 dark:text-zinc-400 mb-6">{description || t.desc}</p>
      {actionText && (
        <button 
          onClick={onClear}
          className="px-6 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-full font-semibold transition-all hover:-translate-y-0.5 hover:shadow-lg hover:shadow-blue-500/30"
        >
          {actionText}
        </button>
      )}
    </div>
  )
}

export default EmptyState

// docs/.vitepress/theme/components/EmptyState.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useData } from 'vitepress';

defineProps<{ icon?: string; title?: string; description?: string; actionText?: string; }>();

const { lang } = useData();
const t = computed(() => {
  return lang.value === 'zh-TW' ? {
    title: '找不到相關結果',
    desc: '請嘗試使用不同的關鍵字，或者檢查拼字是否正確。'
  } : {
    title: 'No results found',
    desc: 'Please try using different keywords or check your spelling.'
  };
});

defineEmits<{ (e: 'clear'): void; }>();
</script>

<template>
  <div class="empty-results">
    <div class="empty-icon">{{ icon || '🔍' }}</div>
    <h3>{{ title || t.title }}</h3>
    <p>{{ description || t.desc }}</p>
    <button v-if="actionText" @click="$emit('clear')" class="clear-btn">{{ actionText }}</button>
  </div>
</template>

<style scoped>
.empty-results {
  text-align: center;
  padding: 80px 24px;
  background: var(--vp-c-bg-alt);
  border-radius: 24px;
  border: 1px dashed var(--vp-c-divider);
  margin-top: 40px;
}

.empty-icon {
  font-size: 48px;
  margin-bottom: 20px;
}

.empty-results h3 {
  font-size: 1.5rem;
  font-weight: 700;
  margin-bottom: 12px;
}

.empty-results p {
  color: var(--vp-c-text-3);
  margin-bottom: 24px;
}

.clear-btn {
  padding: 10px 24px;
  background: var(--vp-c-brand-1);
  color: white;
  border-radius: 99px;
  border: none;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
}

.clear-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 113, 227, 0.3);
}
</style>
