// docs/.vitepress/components/BackToTop.vue
<script setup>
import { onMounted, onUnmounted, ref } from 'vue'

const visible = ref(false)

const handleScroll = () => {
  visible.value = window.scrollY > 300
}

const scrollToTop = () => {
  window.scrollTo({
    top: 0,
    behavior: 'smooth'
  })
}

onMounted(() => {
  window.addEventListener('scroll', handleScroll, { passive: true })
})

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll)
})
</script>

<template>
  <transition name="slide-fade">
    <button
      v-if="visible"
      class="back-to-top"
      aria-label="返回頂部"
      @click="scrollToTop"
    >
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
        <path d="M18 15l-6-6-6 6"/>
      </svg>
    </button>
  </transition>
</template>

<style scoped>
/* Liquid Glass Back to Top - Desktop Only */
.back-to-top {
  display: none; /* Hidden on mobile */
  position: fixed;
  bottom: 28px;
  right: 24px;
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: rgba(var(--vp-c-brand-rgb), 0.85);
  backdrop-filter: blur(20px) saturate(180%);
  -webkit-backdrop-filter: blur(20px) saturate(180%);
  color: white;
  border: 1px solid rgba(255, 255, 255, 0.2);
  align-items: center;
  justify-content: center;
  cursor: pointer;
  z-index: 100;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15), 0 4px 8px rgba(var(--vp-c-brand-rgb), 0.3);
  transition: all 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
}

/* Show only on desktop */
@media (min-width: 960px) {
  .back-to-top {
    display: flex;
  }
}

.back-to-top svg {
  transition: transform 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
}

.back-to-top:hover {
  transform: translateY(-4px) scale(1.05);
  box-shadow: 0 12px 32px rgba(0, 0, 0, 0.2), 0 6px 12px rgba(var(--vp-c-brand-rgb), 0.4);
}

.back-to-top:hover svg {
  transform: translateY(-2px);
}

.back-to-top:active {
  transform: translateY(-2px) scale(0.98);
}

/* Smooth Slide Fade Transition */
.slide-fade-enter-active,
.slide-fade-leave-active {
  transition: opacity 0.4s cubic-bezier(0.34, 1.56, 0.64, 1), 
              transform 0.4s cubic-bezier(0.34, 1.56, 0.64, 1);
}

.slide-fade-enter-from {
  opacity: 0;
  transform: translateY(20px) scale(0.9);
}

.slide-fade-leave-to {
  opacity: 0;
  transform: translateY(20px) scale(0.9);
}

.dark .back-to-top {
  background: rgba(255, 255, 255, 0.12);
  border-color: rgba(255, 255, 255, 0.15);
}

.dark .back-to-top:hover {
  background: rgba(255, 255, 255, 0.18);
}
</style>

// components/ui/BackToTop.tsx
"use client"
import React, { useState, useEffect } from 'react'
import { ArrowUp } from 'lucide-react'

const BackToTop: React.FC = () => {
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    const handleScroll = () => {
      const scrollTop = window.pageYOffset || document.documentElement.scrollTop
      const scrollHeight = document.documentElement.scrollHeight - document.documentElement.clientHeight
      const scrollPercentage = (scrollTop / scrollHeight) * 100
      setVisible(scrollPercentage > 20)
    }

    window.addEventListener('scroll', handleScroll, { passive: true })
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  return (
    <button
      onClick={scrollToTop}
      className={`fixed bottom-8 right-8 w-14 h-14 rounded-full bg-blue-600 text-white shadow-2xl shadow-blue-500/40 flex items-center justify-center z-[100] transition-all duration-500 transform ${
        visible ? 'translate-y-0 opacity-100 scale-100' : 'translate-y-10 opacity-0 scale-90 pointer-events-none'
      } hover:scale-110 active:scale-95 group`}
      aria-label="Back to Top"
    >
      <div className="absolute inset-0 rounded-full bg-blue-600 animate-ping opacity-20 group-hover:hidden" />
      <ArrowUp className="w-6 h-6 group-hover:-translate-y-1 transition-transform" />
    </button>
  )
}

export default BackToTop
